### ISSUE TITLE
Image too big cannot be uploaded

### ISSUE THREAD

**Issue by PymZoR** [buckless/admin#152]
https://img.saveur-biere.com/img/p/82-14662-v4_product_img.jpg doesn't work whereas https://img.saveur-biere.com/img/p/416-15911-v4_product_b.jpg is ok

**Comment by gjuchault** [comment]
🍻

**Comment by PymZoR** [comment]
🍻

**Comment by lonk** [comment]
Fixed by https://github.com/buckless/server/pull/192
