### ISSUE TITLE
Code clean

### ISSUE THREAD

**Issue by gjuchault** [buckless/admin#165]
- [x] Remove src/lib/reloadType, use MeanOfPayment table
- [x] Remove useless forms (`<form>`, `<form @submit.prevent>`, etc.)
- [x] Find a way to make html a bit more readable. Create mixins with basic props that we put everywhere
- [x] Remove every calculation out of HTML scope (`{{ price.amount | price(true) }} TTC <span v-if="modObject.vat > 0">({{ price.amount/(1+modObject.vat/100) | price(true) }} HT)</span>`)
- [x] Create a file for ObjectInfo, ObjectEdit and ObjectRemove (this will clean a *lot*)
- [x] `inputArticle` looks like a computed, but it actually does stuff and return computed data
- [x] Image parser should be in its own file. No need for `const vm = this;`, arrow functions ftw
- [x] Move maths out of `createPeriodPoint`
- [x] Swap `map` and `filter` when using this : `arr.map(...).filter(a => a)` (Devices.vue:248)
- [x] Choose another datetimepicker
- [x] Move math out of Promotions.vue. Change names: `promotionsFormat`
- [x] Prefix components (`<Sidebar>` -> `<b-sidebar>`)

**Comment by gjuchault** [comment]
- [ ] Prefix components (`<Sidebar>` -> `<b-sidebar>`)

**Comment by lonk** [comment]
Finally fixed when merging #176
